#!/usr/bin/env python
# coding: utf-8

# -----------------------------
# Required Imports
# -----------------------------
import os
from dotenv import load_dotenv
from typing import Any, Text, Dict, List

from rasa_sdk import Action, Tracker
from rasa_sdk.executor import CollectingDispatcher

from openai import OpenAI


# -----------------------------
# Function to get response from ChatGPT
# -----------------------------
def get_answers_from_chatgpt(user_text: str) -> str:
    """
    Takes user text as input and returns response generated by ChatGPT
    """

    # Load environment variables from .env file
    load_dotenv()

    # Initialize OpenAI client
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

    # Call Chat Completion API
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "user", "content": user_text}
        ],
        max_tokens=512,
        temperature=0.5
    )

    return response.choices[0].message.content


# -----------------------------
# Rasa Custom Action Class
# -----------------------------
class SimpleChatGPTAction(Action):
    """
    Rasa action to send user text to ChatGPT
    and return the generated response
    """

    def name(self) -> Text:
        return "action_chatgpt_response"

    def run(
        self,
        dispatcher: CollectingDispatcher,
        tracker: Tracker,
        domain: Dict[Text, Any]
    ) -> List[Dict[Text, Any]]:

        # Get latest user message
        user_text = tracker.latest_message.get("text")

        if not user_text:
            dispatcher.utter_message(text="I didn't understand that.")
            return []

        # Get ChatGPT response
        chatgpt_response = get_answers_from_chatgpt(user_text)

        # Send response back to user
        dispatcher.utter_message(text=chatgpt_response)

        return []
